#!/bin/sh /etc/rc.common
# K2-OpenHost: at boot, power-cycle the K2 boards, start them with Creality's
# mcu_update and only then start the bridges (/usr/sbin/k2oh-mcu-start).
# The bridges have no start link of their own: k2oh-mcu starts them.

START=54
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/k2oh-mcu-start
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
