#!/bin/sh /etc/rc.common
# K2-OpenHost: one bridge process per K2 bus (procd restarts them).
#   ttyGS0 <-> ttyS2  Main MCU
#   ttyGS1 <-> ttyS3  Nozzle MCU
#   ttyGS2 <-> ttyS5  RS-485 / CFS / closed-loop motors

START=56
STOP=10
USE_PROCD=1

bridge() {
	procd_open_instance "$1"
	procd_set_param command /usr/bin/python3 /usr/bin/k2oh-bridge "$2" "$3"
	procd_set_param respawn 3600 2 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	local n
	for n in 1 2 3 4 5 6 7 8 9 10; do
		[ -c /dev/ttyGS2 ] && break
		sleep 1
	done
	bridge main /dev/ttyGS0 /dev/ttyS2
	bridge nozzle /dev/ttyGS1 /dev/ttyS3
	bridge rs485 /dev/ttyGS2 /dev/ttyS5
}
